'''
This program trains a PPO agent to stabilize a double pendulum system representing a double pendulum model of
suspension. Our goal is to minimize the horizontal displacement (delta x) of the bottom mass (M2)
while force is only applied to the top mass (M1).

PHYSICS MODEL:
- Double Pendulum with masses M1 and M2 connected by rods of L1 and L2
- Equations of Motion (EOM) derived in Double_Pendulum.pdf
- Seismic noise injected at the top pivot point as horizontal acceleration (x_p_ddot)

NOISE MODEL (corrected based on professor feedback):
- Previous noise was a coherent pure sine: 0.02*sin(2pi*1.5*t) — this continuously pumps energy
  into the pendulum at a fixed phase, causing x2 to grow unboundedly. Real seismic noise has
  RANDOM phases per frequency bin so energy doesn't coherently accumulate.
- New model: band-limited noise generated via IFT with random complex phases per bin
  (equivalent to white noise through a low-pass filter / bandpass filter)
- For each episode, a full noise sequence is pre-generated by:
    1. Defining magnitude spectrum (flat between f_low and f_high Hz)
    2. Assigning random phase phi ~ Uniform(0, 2pi) to each frequency bin
    3. Taking IFFT to get time-domain signal: x(t) = IFT{ A(f) * exp(i*phi(f)) }
  This gives physically realistic noise: bounded, broadband, stationary

RL ENVIRONMENT (Gymnasium):
- State/Observation: [th1, th2, th1_dot, th2_dot]
- Action: Continuous force applied to the top mirror (M1)
- Reward: Penalizes bottom mirror displacement (x2^2) and control effort (u^2)

WORKFLOW:
1. Import shared EOM from equations_of_motion.py
2. Initialize LIGOPendulumEnv (pre-generates noise on each reset)
3. Train PPO agent to predict counter-force needed

OUTPUT PLOTS:
- Plot 1: Time domain x2 displacement — RL agent vs passive
- Plot 2: Amplitude Spectral Density (ASD) in m/sqrt(Hz) vs frequency — matches professor's whiteboard
  This is the standard way LIGO measures performance: lower ASD = better isolation
- Plot 3: Learning curve — mean episode reward vs training steps
'''

import numpy as np
import gymnasium as gym
from gymnasium import spaces
from stable_baselines3 import PPO
from stable_baselines3.common.callbacks import BaseCallback
import matplotlib.pyplot as plt
import time
import os

from equations_of_motion import equations_of_motion, M1, M2, L1, L2, G

# simulation parameters
T_SIM    = 20.0   # s — episode duration
DT       = 0.01   # s — timestep
F_MAX    = 10.0   # N — actuator force limit
N_STEPS  = int(T_SIM / DT)  # 2000 steps per episode

# seismic noise parameters
NOISE_AMP  = 0.002  # m/s^2 amplitude per frequency bin
NOISE_FMIN = 0.1    # Hz — lower cutoff
NOISE_FMAX = 5.0    # Hz — upper cutoff (above pendulum resonance ~0.5 Hz)


def generate_seismic_noise(n, dt, seed=None):
    '''
    Generate one episode of seismic noise via IFT with random phases.
    This produces band-limited noise with random phase per frequency bin —
    physically correct model vs a coherent sine wave.

    Method (as discussed with professor):
    - Build magnitude spectrum: flat between f_low and f_high, zero outside
    - Assign random complex phase phi ~ Uniform(0, 2pi) to each bin
    - IFT -> time domain signal that is bounded and non-repeating
    '''
    rng   = np.random.default_rng(seed)
    freqs = np.fft.rfftfreq(n, d=dt)       # frequency bins for rfft

    # flat magnitude within band, zero outside
    mag  = np.zeros(len(freqs))
    mask = (freqs >= NOISE_FMIN) & (freqs <= NOISE_FMAX)
    mag[mask] = NOISE_AMP

    # random phase per bin — this is the key fix
    # without random phases, a pure sine would coherently pump energy into the pendulum every cycle
    phase    = rng.uniform(0, 2 * np.pi, len(freqs))
    spectrum = mag * np.exp(1j * phase)

    # IFFT to time domain, scale by sqrt(n) to preserve amplitude
    noise = np.fft.irfft(spectrum, n=n) * np.sqrt(n)
    return noise  # shape (n,), units m/s^2


class LIGOPendulumEnv(gym.Env):
    def __init__(self):
        super().__init__()

        # action: horizontal force on M1, -10 to 10 N
        self.action_space = spaces.Box(low=-F_MAX, high=F_MAX, shape=(1,), dtype=np.float32)

        # observation: [th1, th2, w1, w2]
        self.observation_space = spaces.Box(low=-np.inf, high=np.inf, shape=(4,), dtype=np.float32)

        self.state        = None
        self.dt           = DT
        self.current_step = 0
        self.noise_seq    = None  # pre-generated noise for this episode

    def reset(self, seed=None, options=None):
        super().reset(seed=seed)

        # start near equilibrium — small random perturbation just breaks symmetry
        # (large initial tilts dominate over noise making control problem ill-conditioned)
        self.state = np.random.uniform(low=-0.01, high=0.01, size=(4,)).astype(np.float32)

        self.current_step = 0

        # pre-generate the entire noise sequence for this episode
        # using a random seed each time so every episode has different noise
        ep_seed = np.random.randint(0, 2**31)
        self.noise_seq = generate_seismic_noise(N_STEPS + 10, self.dt, seed=ep_seed)

        return self.state, {}

    def step(self, action):
        force_val = float(action[0])

        # look up pre-generated seismic noise for this timestep
        x_p_ddot = float(self.noise_seq[self.current_step])
        self.current_step += 1

        # integrate equations of motion
        # force_val = control force on M1 (agent's action)
        # x_p_ddot  = pivot acceleration (seismic disturbance)
        self.state = self.state + equations_of_motion(self.state, x_p_ddot, force_val) * self.dt

        th1, th2 = self.state[0], self.state[1]
        x2 = L1 * np.sin(th1) + L2 * np.sin(th2)

        # reward: penalise displacement and control effort
        # -x2^2 = main goal (keep bottom mirror still)
        # -0.1*force^2 = effort penalty (don't thrash the actuator)
        reward = -(x2**2) - 0.1 * (force_val**2)

        # terminate if pendulum falls past 90 degrees
        terminated = bool(np.abs(th1) > np.pi/2 or np.abs(th2) > np.pi/2)

        # also terminate if we've used all pre-generated noise
        if self.current_step >= len(self.noise_seq) - 1:
            terminated = True

        return self.state.astype(np.float32), float(reward), terminated, False, {}


# ---- Progress logger ----
class ProgressLogger(BaseCallback):
    def __init__(self, verbose=0):
        super().__init__(verbose)
        self.first_rew      = None
        self.reward_history = []
        self.steps_history  = []

    def _on_step(self) -> bool:
        if self.first_rew is None and len(self.model.ep_info_buffer) > 0:
            self.first_rew = np.mean([ep['r'] for ep in self.model.ep_info_buffer])
        return True

    def _on_rollout_end(self) -> None:
        if len(self.model.ep_info_buffer) > 0:
            mean_rew = np.mean([ep['r'] for ep in self.model.ep_info_buffer])
            self.reward_history.append(mean_rew)
            self.steps_history.append(self.num_timesteps)

    def _on_training_end(self) -> None:
        print("\n" + "="*32)
        print(" AI PERFORMANCE")
        print("="*32)
        if len(self.model.ep_info_buffer) > 0:
            final_rew = np.mean([ep['r'] for ep in self.model.ep_info_buffer])
            if self.first_rew is not None:
                improvement = ((final_rew - self.first_rew) / abs(self.first_rew)) * 100
                print(f"Initial Reward: {self.first_rew:.4f}")
                print(f"Final Reward:   {final_rew:.4f}")
                print(f"Improvement:    {improvement:.1f}%")
            else:
                print(f"Final Reward: {final_rew:.4f}")
        print("="*32)


# ---- Evaluation simulation ----
def simulate_episode(model, noise_seed=0, use_agent=True):
    '''
    Run one evaluation episode.
    use_agent=True  -> RL agent applies force each step
    use_agent=False -> passive, F=0 (just seismic noise)
    Both use the same noise_seed for a fair comparison.
    '''
    noise = generate_seismic_noise(N_STEPS + 10, DT, seed=noise_seed)
    state = np.random.default_rng(noise_seed).uniform(-0.01, 0.01, size=4).astype(np.float32)

    log_t, log_x2, log_F = [], [], []

    for step in range(N_STEPS):
        t        = (step + 1) * DT
        x_p_ddot = float(noise[step])

        if use_agent:
            action, _ = model.predict(state, deterministic=True)
            force_val = float(np.clip(action[0], -F_MAX, F_MAX))
        else:
            force_val = 0.0

        state = state + equations_of_motion(state, x_p_ddot, force_val) * DT

        th1, th2 = state[0], state[1]
        x2 = L1 * np.sin(th1) + L2 * np.sin(th2)

        log_t.append(t)
        log_x2.append(x2)
        log_F.append(force_val)

        if np.abs(th1) > np.pi/2 or np.abs(th2) > np.pi/2:
            break

    return np.array(log_t), np.array(log_x2), np.array(log_F)


def compute_asd(x, dt):
    '''
    Compute amplitude spectral density (ASD) in units/sqrt(Hz).
    This is the standard LIGO performance metric — lower ASD = better isolation.
    ASD = |FFT(x)| * sqrt(2 * dt / N)
    '''
    n    = len(x)
    freq = np.fft.rfftfreq(n, d=dt)
    fft  = np.fft.rfft(x)
    asd  = np.abs(fft) * np.sqrt(2 * dt / n)   # one-sided ASD
    return freq[1:], asd[1:]   # skip DC (f=0)


# ---- Main ----
if __name__ == "__main__":

    env   = LIGOPendulumEnv()
    model = PPO("MlpPolicy", env, verbose=1, n_steps=4096)
    logger = ProgressLogger()

    print("Training the RL agent...")
    model.learn(total_timesteps=500000, callback=logger)
    model.save("pendulum_model")
    print("Training finished!")

    # evaluate with multiple seeds and average for stable ASD estimate
    print("\nRunning evaluation episodes...")
    eval_seed = int(time.time()) % 100_000

    t_p, x2_p, F_p = simulate_episode(model, noise_seed=eval_seed, use_agent=False)
    t_r, x2_r, F_r = simulate_episode(model, noise_seed=eval_seed, use_agent=True)

    rms_p = np.std(x2_p) * 1e3
    rms_r = np.std(x2_r) * 1e3
    print(f"Passive RMS x2: {rms_p:.3f} mm")
    print(f"RL agent RMS x2: {rms_r:.3f} mm")
    print(f"Improvement: {rms_p/max(rms_r,1e-9):.2f}x")

    # ---- PLOT 1: time domain ----
    fig, axes = plt.subplots(2, 1, figsize=(11, 7), sharex=True)
    fig.suptitle(f"LIGO Double Pendulum — RL Agent vs Passive (seed={eval_seed})", fontsize=13)

    axes[0].plot(t_r, x2_r * 1e3, color="steelblue", lw=1.2, label="RL agent",            alpha=0.9)
    axes[0].plot(t_p, x2_p * 1e3, color="gray",      lw=1.5, label="Passive (no control)", alpha=0.9)
    axes[0].set_ylabel("x₂ (mm)")
    axes[0].legend(); axes[0].grid(alpha=0.4)

    axes[1].plot(t_r, F_r, color="crimson", lw=1.0, label="RL force")
    axes[1].axhline( F_MAX, ls="--", color="k", lw=0.7, label=f"±{F_MAX} N limit")
    axes[1].axhline(-F_MAX, ls="--", color="k", lw=0.7)
    f_range = max(np.abs(F_r).max(), 0.1)
    axes[1].set_ylim(-f_range * 1.3, f_range * 1.3)
    axes[1].set_ylabel("Control force F (N)")
    axes[1].set_xlabel("Time (s)")
    axes[1].legend(); axes[1].grid(alpha=0.4)

    plt.tight_layout()
    plt.savefig(f"rl_result_seed{eval_seed}.png", dpi=150)
    plt.show()

    # ---- PLOT 2: ASD — matches professor's whiteboard format ----
    # this is how LIGO measures isolation: m/sqrt(Hz) vs Hz, log-log scale
    # controlled ASD should be LOWER than uncontrolled, especially near resonance (~0.5 Hz)
    freq_p, asd_p = compute_asd(x2_p, DT)
    freq_r, asd_r = compute_asd(x2_r, DT)

    fig2, axes2 = plt.subplots(1, 2, figsize=(13, 5))
    fig2.suptitle("Amplitude Spectral Density — RL Agent vs Passive", fontsize=13)

    # left: displacement ASD (matches professor's left plot)
    axes2[0].loglog(freq_p, asd_p, color="gray",      lw=1.5, label="Passive (uncontrolled)")
    axes2[0].loglog(freq_r, asd_r, color="steelblue", lw=1.5, label="RL agent (controlled)")
    axes2[0].axvline(0.5, ls=":", color="k", lw=0.8, label="Pendulum resonance ~0.5 Hz")
    axes2[0].set_xlabel("Frequency (Hz)")
    axes2[0].set_ylabel("x₂ ASD (m/√Hz)")
    axes2[0].set_xlim([0.1, 10])
    axes2[0].legend(); axes2[0].grid(alpha=0.3, which="both")
    axes2[0].set_title("Displacement ASD")

    # right: force ASD (matches professor's right plot)
    freq_f, asd_f = compute_asd(F_r, DT)
    axes2[1].loglog(freq_f, asd_f, color="crimson", lw=1.5, label="RL control force")
    axes2[1].set_xlabel("Frequency (Hz)")
    axes2[1].set_ylabel("Force ASD (N/√Hz)")
    axes2[1].set_xlim([0.1, 10])
    axes2[1].legend(); axes2[1].grid(alpha=0.3, which="both")
    axes2[1].set_title("Control Force ASD")

    plt.tight_layout()
    plt.savefig(f"rl_asd_seed{eval_seed}.png", dpi=150)
    plt.show()

    # ---- PLOT 3: learning curve ----
    if len(logger.reward_history) > 1:
        fig3, ax3 = plt.subplots(figsize=(10, 4))
        fig3.suptitle("RL Agent Learning Curve", fontsize=13)
        ax3.plot(logger.steps_history, logger.reward_history,
                 color="steelblue", lw=1.2, label="Mean reward per rollout", alpha=0.6)
        if len(logger.reward_history) >= 5:
            smoothed = np.convolve(logger.reward_history, np.ones(5)/5, mode='valid')
            ax3.plot(logger.steps_history[4:], smoothed,
                     color="crimson", lw=2.0, label="5-batch rolling avg (trend)")
        ax3.set_xlabel("Training steps")
        ax3.set_ylabel("Mean episode reward")
        ax3.legend(); ax3.grid(alpha=0.4)
        plt.tight_layout()
        plt.savefig("rl_learning_curve.png", dpi=150)
        plt.show()


'''
# resume training from saved model
if __name__ == "__main__":
    env       = LIGOPendulumEnv()
    save_name = "pendulum_model2"

    if os.path.exists(f"{save_name}.zip"):
        print(f"Loading {save_name} to continue training...")
        model = PPO.load(save_name, env=env)
    else:
        print(f"Starting {save_name} from scratch...")
        model = PPO("MlpPolicy", env, verbose=1, n_steps=4096)

    logger = ProgressLogger()
    model.learn(total_timesteps=500000, callback=logger)
    model.save(save_name)
    print(f"Saved to {save_name}.zip")
'''
